// Auto-generated by scripts/generateRegistry.ts — do not edit manually
import { ComponentType } from 'react'
import ExampleGame from '@/components/games/example-game/ExampleGame'
import ChickenCrossing from '@/components/games/chicken-crossing/ChickenCrossing'

const gameRegistry: Record<string, ComponentType> = {
  'example-game': ExampleGame,
  'chicken-crossing': ChickenCrossing,
}

export { gameRegistry }
